name: deploy the application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Clone repository
        uses: actions/checkout@v4

      # Step 2: Copy files to EC2 (home folder)
      - name: Copy files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/app/"

      # Step 3: Move files to Nginx folder and restart
      - name: Deploy to Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/app/* /var/www/html/
            sudo systemctl restart nginx
